/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostedRouteImport } from './routes/hosted'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnHostedRouteImport } from './routes/en.hosted'
import { Route as EnPricingRouteImport } from './routes/en.pricing'
import { Route as EnDocsIndexRouteImport } from './routes/en.docs.index'
import { Route as EnDocsSlugRouteImport } from './routes/en.docs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedRoute = HostedRouteImport.update({
  id: '/hosted',
  path: '/hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHostedRoute = EnHostedRouteImport.update({
  id: '/en/hosted',
  path: '/en/hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDocsIndexRoute = EnDocsIndexRouteImport.update({
  id: '/en/docs/',
  path: '/en/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDocsSlugRoute = EnDocsSlugRouteImport.update({
  id: '/en/docs/$slug',
  path: '/en/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hosted': typeof HostedRoute
  '/pricing': typeof PricingRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/en/hosted': typeof EnHostedRoute
  '/en/pricing': typeof EnPricingRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/docs/': typeof EnDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hosted': typeof HostedRoute
  '/pricing': typeof PricingRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/en/hosted': typeof EnHostedRoute
  '/en/pricing': typeof EnPricingRoute
  '/docs': typeof DocsIndexRoute
  '/en': typeof EnIndexRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/docs': typeof EnDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hosted': typeof HostedRoute
  '/pricing': typeof PricingRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/en/hosted': typeof EnHostedRoute
  '/en/pricing': typeof EnPricingRoute
  '/docs/': typeof DocsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/docs/$slug': typeof EnDocsSlugRoute
  '/en/docs/': typeof EnDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hosted'
    | '/pricing'
    | '/docs/$slug'
    | '/en/hosted'
    | '/en/pricing'
    | '/docs/'
    | '/en/'
    | '/en/docs/$slug'
    | '/en/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hosted'
    | '/pricing'
    | '/docs/$slug'
    | '/en/hosted'
    | '/en/pricing'
    | '/docs'
    | '/en'
    | '/en/docs/$slug'
    | '/en/docs'
  id:
    | '__root__'
    | '/'
    | '/hosted'
    | '/pricing'
    | '/docs/$slug'
    | '/en/hosted'
    | '/en/pricing'
    | '/docs/'
    | '/en/'
    | '/en/docs/$slug'
    | '/en/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostedRoute: typeof HostedRoute
  PricingRoute: typeof PricingRoute
  DocsSlugRoute: typeof DocsSlugRoute
  EnHostedRoute: typeof EnHostedRoute
  EnPricingRoute: typeof EnPricingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnDocsSlugRoute: typeof EnDocsSlugRoute
  EnDocsIndexRoute: typeof EnDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted': {
      id: '/hosted'
      path: '/hosted'
      fullPath: '/hosted'
      preLoaderRoute: typeof HostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/hosted': {
      id: '/en/hosted'
      path: '/en/hosted'
      fullPath: '/en/hosted'
      preLoaderRoute: typeof EnHostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/docs/': {
      id: '/en/docs/'
      path: '/en/docs'
      fullPath: '/en/docs/'
      preLoaderRoute: typeof EnDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/docs/$slug': {
      id: '/en/docs/$slug'
      path: '/en/docs/$slug'
      fullPath: '/en/docs/$slug'
      preLoaderRoute: typeof EnDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostedRoute: HostedRoute,
  PricingRoute: PricingRoute,
  DocsSlugRoute: DocsSlugRoute,
  EnHostedRoute: EnHostedRoute,
  EnPricingRoute: EnPricingRoute,
  DocsIndexRoute: DocsIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnDocsSlugRoute: EnDocsSlugRoute,
  EnDocsIndexRoute: EnDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
